### ISSUE TITLE
dsc_resource does not set an execution policy on the invoked powershell

### ISSUE THREAD

**Issue by mwrock** [chef-cookbooks/dsc#14]
I was testing this on a fresh windows 8.1 vm. windows 8.1 (as well as 8 and 2012) have a default execution policy of `restricted`. I received an error:

```
Importing module MSFT_xRemoteFile failed with error - File C:\\Program Files\\Win\r\ndowsPowerShell\\Modules\\xPSDesiredStateConfiguration\\DscResources\\MSFT_xRemoteFile\\MSFT_xRemoteFile.psm1 cannot be loaded because running scripts is disabled on this system.
```

I was able to get around this by adding this to the top of my recipe:

```
powershell_script "set execution policy" do
   code "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force"
end
```

But the PowershellCmdlet class really should set the execution policy of the powershell process it creates.

**Comment by ferventcoder** [comment]
Ran into this yesterday as well.

**Comment by tas50** [comment]
Sorry for the late response, but we've deprecated since repository as the dsc functionality is now part of the chef-client itself.  I'm going to close this issue out at this point.  If you're still encountering this problem you'll want to file it against the chef project itself.
