### ISSUE TITLE
 property attribute doesn't accept an array

### ISSUE THREAD

**Issue by matthewhatch** [chef-cookbooks/dsc#17]
I have a custom DSC resource that accepts an array for one of the parameters and when I run chef-client I get an error. This is what I have in the recipe:

```ruby
dsc_resource 'SetPermission-IISLogs' do
  resource :Custom_PermissionsResource
  property :Path, 'd:\path\to\logs'
  property :Identity, 'SomeGroup'
  property :Permission, ["Permission1","Permission2"]
end
```
which maps to the following in DSC config:

```powershell
Custom_PermissionsResource 'SetPermission-IISLogs'
{
    Path = 'd:\path\to\logs'
    Identity = 'SomeGroup'
    Permission, @("Permission1","Permission2")
}
```
When I look at the Desired State Configuration event log, I see that the value for the Permission property is passed to DSC as '[Permission2,Permission2]' and should be an array.

I See that the rfc (https://github.com/chef/chef-rfc/blob/adamed/dsc/rfc015-powershell-dsc-resources.md#type-safety-for-dsc_resource-property-attributes) does not specify arrays, so maybe this is a suggestions and not an issue.

**Comment by matthewhatch** [comment]
So it appears that it will accept an array in the following format (I thought I tested this before submitting the issue)

```ruby
dsc_resource 'SetPermission-IISLogs' do
  resource :Custom_PermissionsResource
  property :Path, 'd:\path\to\logs'
  property :Identity, 'SomeGroup'
  property :Permission, "Permission1","Permission2"
end
```

**Comment by tas50** [comment]
Sorry for the late response, but we've deprecated since repository as the dsc functionality is now part of the chef-client itself.  I'm going to close this issue out at this point.  If you're still encountering this problem you'll want to file it against the chef project itself.
